---
framework: jest
preRun:
  command:
    - yarn install
preMerge:
  pattern:
    - "scripts/__tests__/*-test.js"
    - "packages/**/__tests__/*-test.js"
postMerge:
  pattern:
    - "scripts/__tests__/*-test.